[package]
name = "bifrost-bancor"
version = "0.8.0"
authors = ["Herry Ho <herry.heyi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-system = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
serde = { version = "1.0.124", optional = true }
orml-traits = { version = "0.4.1-dev", default-features = false }
orml-tokens = { version = "0.4.1-dev", default-features = false }
node-primitives = { path = "../../node/primitives", default-features = false }
num-integer = { version = "0.1.36", default-features = false }

[dev-dependencies]
sp-io = { version = "3.0.0", default-features = false, features = ["std"] }
sp-core = { version = "3.0.0", default-features = false, features = ["std"] }
sp-runtime = { version = "3.0.0", default-features = false, features = ["std"] }
bifrost-assets = { path = "../assets", default-features = false, features = ["std"] }
node-primitives = { path = "../../node/primitives", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-system/std",
    "frame-support/std",
    "serde/std",
    "orml-traits/std",
    "orml-tokens/std",
    "num-integer/std"
]