[package]
name = "bifrost-salp"
version = "0.8.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
node-primitives = { path = "../../node/primitives", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.4", default-features = false }
xcm-support = { path = "../../xcm-support", default-features = false }
orml-traits = { version = "0.4.1-dev", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"node-primitives/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"sp-runtime/std",
	"orml-traits/std",
	"xcm/std",
	"xcm-support/std",
]
