name: ci-build

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:
      - name: Check to latest commit
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_bifrost.sock
        run: |
          [ ! -d "${HOME}/.ssh/" ] && mkdir -p ${HOME}/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${HOME}/.ssh/github_actions
          chmod 600 ${HOME}/.ssh/github_actions
          [ ! -e "/tmp/ssh_bifrost.sock" ]  && eval "$(ssh-agent -a /tmp/ssh_bifrost.sock)"
          ssh-add ${HOME}/.ssh/github_actions
      - name: Cache cargo registry and index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true
      - name: Check
        env:
          SSH_AUTH_SOCK: /tmp/ssh_bifrost.sock
        run: make check-bifrost
      - name: Run tests
        run: make test-bifrost
      - uses: 8398a7/action-slack@v3
        if: always() && (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
        with:
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,ref,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PULLREQUEST_WEBHOOK_URL }}